var annotated_dup =
[
    [ "CLI", null, [
      [ "ArgumentMismatch", "classCLI_1_1ArgumentMismatch.html", null ],
      [ "BadNameString", "classCLI_1_1BadNameString.html", null ],
      [ "CallForHelp", "classCLI_1_1CallForHelp.html", null ],
      [ "ConstructionError", "classCLI_1_1ConstructionError.html", null ],
      [ "ConversionError", "classCLI_1_1ConversionError.html", null ],
      [ "Error", "classCLI_1_1Error.html", "classCLI_1_1Error" ],
      [ "ExcludesError", "classCLI_1_1ExcludesError.html", null ],
      [ "ExtrasError", "classCLI_1_1ExtrasError.html", null ],
      [ "FileError", "classCLI_1_1FileError.html", null ],
      [ "HorribleError", "classCLI_1_1HorribleError.html", null ],
      [ "IncorrectConstruction", "classCLI_1_1IncorrectConstruction.html", null ],
      [ "INIError", "classCLI_1_1INIError.html", null ],
      [ "InvalidError", "classCLI_1_1InvalidError.html", null ],
      [ "is_bool", "structCLI_1_1is__bool.html", null ],
      [ "is_bool< bool >", "structCLI_1_1is__bool_3_01bool_01_4.html", null ],
      [ "is_vector", "structCLI_1_1is__vector.html", null ],
      [ "is_vector< std::vector< T, A > >", "structCLI_1_1is__vector_3_01std_1_1vector_3_01T_00_01A_01_4_01_4.html", null ],
      [ "OptionAlreadyAdded", "classCLI_1_1OptionAlreadyAdded.html", null ],
      [ "OptionNotFound", "classCLI_1_1OptionNotFound.html", null ],
      [ "ParseError", "classCLI_1_1ParseError.html", null ],
      [ "RequiredError", "classCLI_1_1RequiredError.html", null ],
      [ "RequiresError", "classCLI_1_1RequiresError.html", null ],
      [ "RuntimeError", "classCLI_1_1RuntimeError.html", null ],
      [ "Success", "classCLI_1_1Success.html", null ],
      [ "ValidationError", "classCLI_1_1ValidationError.html", null ]
    ] ],
    [ "AnimOptions", "structAnimOptions.html", "structAnimOptions" ],
    [ "corrfindOptions", "structcorrfindOptions.html", "structcorrfindOptions" ],
    [ "corrimgOptions", "structcorrimgOptions.html", "structcorrimgOptions" ],
    [ "corrnhdrOptions", "structcorrnhdrOptions.html", "structcorrnhdrOptions" ],
    [ "corrOptions", "structcorrOptions.html", "structcorrOptions" ],
    [ "CziDimensionEntryDV1", "structCziDimensionEntryDV1.html", "structCziDimensionEntryDV1" ],
    [ "CziDirectoryEntryDV", "structCziDirectoryEntryDV.html", "structCziDirectoryEntryDV" ],
    [ "CziDirectoryEntryDV_HeaderOnly", "structCziDirectoryEntryDV__HeaderOnly.html", "structCziDirectoryEntryDV__HeaderOnly" ],
    [ "CziHeaderInfo", "structCziHeaderInfo.html", "structCziHeaderInfo" ],
    [ "CziMetadataSegmentHeaderPart", "structCziMetadataSegmentHeaderPart.html", "structCziMetadataSegmentHeaderPart" ],
    [ "CziSubBlockSegment", "structCziSubBlockSegment.html", "structCziSubBlockSegment" ],
    [ "CziSubBlockSegment_HeaderOnly", "structCziSubBlockSegment__HeaderOnly.html", "structCziSubBlockSegment__HeaderOnly" ],
    [ "ImageDims", "structImageDims.html", "structImageDims" ],
    [ "LSPException", "classLSPException.html", "classLSPException" ],
    [ "nhdrCheckOptions", "structnhdrCheckOptions.html", "structnhdrCheckOptions" ],
    [ "SID", "structSID.html", "structSID" ],
    [ "SkimOptions", "structSkimOptions.html", "structSkimOptions" ],
    [ "untextOptions", "structuntextOptions.html", "structuntextOptions" ]
];