lsp resamp -i corr_nhdr/ -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/ -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/ -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/ -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/ -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/ -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/ -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/ -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/ -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/ -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/ -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/ -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/ -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/ -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/ -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/ -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/ -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/ -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/ -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/ -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/ -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/ -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/ -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/ -g grid.txt -k box -o resamp -v 0