lsp resamp -i corr_nhdr/263.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/264.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/265.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/266.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/267.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/268.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/269.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/270.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/271.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/272.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/273.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/274.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/275.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/276.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/277.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/278.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/279.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/280.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/281.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/282.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/283.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/284.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/285.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/286.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/287.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/288.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/289.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/290.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/291.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/292.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/293.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/294.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/295.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/296.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/297.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/298.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/299.nhdr -g grid.txt -k box -o resamp -v 0
lsp resamp -i corr_nhdr/230.nhdr -g grid.txt -k box -o resamp -v 0